# This is a basic workflow to help you get started with Actions

name: convert doxc to epub and mobi

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  convert:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
      - uses: actions/checkout@v2

      - name: install calibre
        run: sudo apt-get install calibre
        
      - name: create output folder
        run: |
          mkdir epub-books
          cd epub-books
          mkdir epub
          mkdir mobi
        
      - name: loop and convert to epub
        run: for file in ./*.docx; do ebook-convert "${file##*/}" epub-books/epub/"${file%.*}".epub --enable-heuristics --no-default-epub-cover --insert-blank-line --publisher Publizm --chapter "//*[((name()='h1' or name()='h2') and re:test(., 'chapter|book|I|kapittel|section|part\s+', 'i')) or @class = 'chapter']"; done
        
      - name: loop and convert to mobi
        run: for file in ./*.docx; do ebook-convert "${file##*/}" epub-books/mobi/"${file%.*}".mobi --enable-heuristics --insert-blank-line --publisher Publizm --chapter "//*[((name()='h1' or name()='h2') and re:test(., 'chapter|book|I|kapittel|section|part\s+', 'i')) or @class = 'chapter']"; done
        
      - name: upload epub files
        uses: actions/upload-artifact@v2
        with:
          name: upload file
          path: epub-books

          

